anthropic:
  env:
    - name: ANTHROPIC_API_KEY
      file: ${HOME}/.keys/anthropic.api.key
  models:
    - name: claude-3-7-sonnet-latest
      settings:
        max_tokens: 20480
        thinking:
          type: enabled
          budget_tokens: 10240

deepseek:
  env:
    - name: DEEPSEEK_API_KEY
      file: ${HOME}/.keys/deepseek.api.key
  models:
    - name: deepseek-chat
      settings:
        max_tokens: 8192
        frequency_penalty: 0
        presence_penalty: 0
        response_format:
          type: text
        temperature: 0.6
        top_p: 1
    - name: deepseek-reasoner
      settings:
        max_tokens: 8192
        frequency_penalty: 0
        presence_penalty: 0
        response_format:
          type: text
        temperature: 0.6
        top_p: 1

fireworks:
  env:
    - name: FIREWORKS_API_KEY
      file: ${HOME}/.keys/fireworks.api.key
  models:
    - name: accounts/fireworks/models/deepseek-r1
      settings:
        max_tokens: 40960
        top_p: 1
        top_k: 40
        presence_penalty: 0
        frequency_penalty: 0
        temperature: 0.6
    - name: accounts/fireworks/models/qwq-32b
      settings:
        max_tokens: 81920
        top_p: 1
        top_k: 40
        presence_penalty: 0
        frequency_penalty: 0
        temperature: 0.6

google-gla:
  env:
    - name: GEMINI_API_KEY
      file: ${HOME}/.keys/gemini.api.key
  models:
    - name: gemini-2.0-flash
      settings:
        max_tokens: 8192

openai:
  env:
    - name: OPENAI_API_KEY
      file: ${HOME}/.keys/openai.api.key
  models:
    - name: gpt-4o
      settings:
        max_tokens: 8192
    - name: o1-mini
      settings:
        max_tokens: 8192
    - name: o3-mini
      settings:
