openai:
  env:
    - name: OPENAI_API_KEY
      file: ${HOME}/.keys/openai.api.key
  models:
    gpt-4o:
      settings:
        max_tokens: 16000
    o1-mini:
      settings:
        max_tokens: 20480
    o3-mini:
      settings:
        max_tokens: 20480

anthropic:
  env:
    - name: ANTHROPIC_API_KEY
      file: ${HOME}/.keys/anthropic.api.key
  models:
    claude-3.7:
      name: claude-3-7-sonnet-latest
      settings:
        max_tokens: 20480
        thinking:
          type: enabled
          budget_tokens: 10240

gemini:
  env:
    - name: GEMINI_API_KEY
      file: ${HOME}/.keys/gemini.api.key
  models:
    gemini-2.0-flash:
      settings:
        max_tokens: 20480
    gemini-2.5-pro:
      name: gemini-2.5-pro-preview-03-25
      settings:
        max_tokens: 20480

deepseek:
  env:
    - name: DEEPSEEK_API_KEY
      file: ${HOME}/.keys/deepseek.api.key
  models:
    deepseek-chat:
      settings:
        max_tokens: 20480
        frequency_penalty: 0
        presence_penalty: 0
        response_format:
          type: text
        temperature: 0.6
        top_p: 1
    deepseek-reasoner:
      settings:
        max_tokens: 8192
        frequency_penalty: 0
        presence_penalty: 0
        response_format:
          type: text
        temperature: 0.6
        top_p: 1

together:
  env:
    - name: TOGETHER_API_KEY
      file: ${HOME}/.keys/together.api.key
  models:
    deepseek-r1:
      name: deepseek-ai/DeepSeek-R1
      settings:
        max_tokens: 40960
    deepseek-v3:
      name: deepseek-ai/DeepSeek-V3
      settings:
        max_tokens: 40960

fireworks:
  env:
    - name: FIREWORKS_API_KEY
      file: ${HOME}/.keys/fireworks.api.key
  models:
    deepseek-r1:
      name: accounts/fireworks/models/deepseek-r1-basic
      settings:
        max_tokens: 40960
        top_p: 1
        top_k: 40
        presence_penalty: 0
        frequency_penalty: 0
        temperature: 0.6
    deepseek-v3:
      name: accounts/fireworks/models/deepseek-v3-0324
      settings:
        max_tokens: 40960
        top_p: 1
        top_k: 40
        presence_penalty: 0
        frequency_penalty: 0
        temperature: 0.6
    qwq-32b:
      name: accounts/fireworks/models/qwq-32b
      settings:
        max_tokens: 81920
        top_p: 1
        top_k: 40
        presence_penalty: 0
        frequency_penalty: 0
        temperature: 0.6
