
rsync:
  run_upload: true
  rsync_source_prefix: "~/.trainer"
  rsync_target_prefix: "192.168.5.202:.trainer"
  rsync_path: "mkdir -p .trainer/{rsync_name} && rsync"
  timeout: 10
  retries: 3
  file_list:
    - adapter_config.json
    - adapter_model.safetensors

vllm:
  host: 192.168.5.202
  port: 8091
  timeout: 60
  retries: 3   # sleep 2^retries seconds between retries
  api_key_path: "~/.keys/local.api.key"

test:
  prefix_tag: "test_0.1.0"
  loop:
    - type: trainer.grpo
      epoch_id: "0"
      block_id: "0"
      input_tag: "KC_0.1.0_14B_000_00"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
    - type: trainer.rft
      epoch_id: "0"
      block_id: "0"
      input_tag: "KC_0.1.0_14B_000_00"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
    - type: trainer.grpo
      epoch_id: "0"
      block_id: "1"
      input_tag: "KC_0.1.0_14B_000_01"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
    - type: trainer.rft
      epoch_id: "0"
      block_id: "1"
      input_tag: "KC_0.1.0_14B_000_01"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
    - type: trainer.grpo
      epoch_id: "0"
      block_id: "1"
      input_tag: "KC_0.1.0_14B_000_02"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
    - type: trainer.rft
      epoch_id: "0"
      block_id: "1"
      input_tag: "KC_0.1.0_14B_000_02"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
    - type: trainer.grpo
      epoch_id: "0"
      block_id: "1"
      input_tag: "KC_0.1.0_14B_000_03"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
    - type: trainer.rft
      epoch_id: "0"
      block_id: "1"
      input_tag: "KC_0.1.0_14B_000_03"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
    - type: trainer.grpo
      epoch_id: "0"
      block_id: "1"
      input_tag: "KC_0.1.0_14B_000_04"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
    - type: trainer.rft
      epoch_id: "0"
      block_id: "1"
      input_tag: "KC_0.1.0_14B_000_04"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
    - type: trainer.grpo
      epoch_id: "0"
      block_id: "1"
      input_tag: "KC_0.1.0_14B_000_05"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
    - type: trainer.rft
      epoch_id: "0"
      block_id: "1"
      input_tag: "KC_0.1.0_14B_000_05"
      input_dir: ~/.codeGenEval
      output_dir: ~/.trainer
