
rsync:
  rsync_source_prefix: "~/.trainer"
  rsync_target_prefix: "192.168.5.202:.trainer"
  timeout: 10
  retries: 3
  file_list:
    - adapter_config.json
    - adapter_model.safetensors

vllm:
  host: 192.168.5.202
  port: 8091
  timeout: 60
  retries: 3   # sleep 2^retries seconds between retries
  api_key_path: "~/.keys/local.api.key"
