registry:
  TC_0.1.0_32B.c:
    short_name: "t32c"
    config_path: "workflow/32B.c.yaml"
    data_dir: "~/.workflow"
  TC_0.1.0_32B.d:
    short_name: "t32d"
    config_path: "workflow/32B.d.yaml"
    data_dir: "~/.workflow"
  TC_0.1.0_32B.e:
    short_name: "t32e"
    config_path: "workflow/32B.e.yaml"
    data_dir: "~/.workflow"
  TC_0.1.0_32B.f:
    short_name: "t32f"
    config_path: "workflow/32B.f.yaml"
    data_dir: "~/.workflow"
  TC_0.1.0_32B.g:
    short_name: "t32g"
    config_path: "workflow/32B.g.yaml"
    data_dir: "~/.workflow"
  TC_0.1.0_32B.h:
    short_name: "t32h"
    config_path: "workflow/32B.h.yaml"
    data_dir: "~/.workflow"
  test: # please do not remove, this is used by unit tests
    short_name: "test"
    config_path: "workflow/test.yaml"
    data_dir: "~/.workflow"
  my_tag.a:
    short_name: "ma"
    config_path: "workflow/my_tag.a.yaml"
    data_dir: "shared/.workflow"
  cudacoder_eval_one_turn.test: # run make sync_config to update the config file in the shared folder
    short_name: "cudacoder_eval2"
    config_path: "shared/config/workflow/cudacoder_eval_one_turn.test.yaml"
    data_dir: "shared/.workflow"
  cudacoder_eval_4_turn.qwen32b:
    short_name: "cudacoder_eval_4"
    config_path: "shared/config/workflow/cudacoder_eval_4_turn.qwen32b.yaml"
    data_dir: "shared/.workflow"
  cudacoder_eval_4_turn.qwen32b_repeat:
    short_name: "cudacoder_eval_4"
    config_path: "shared/config/workflow/cudacoder_eval_4_turn.qwen32b_repeat.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t01:
    short_name: "cudacoder_gspo_qwen32b_t01"
    config_path: "shared/config/workflow/cudacoder_gspo_qwen32b.t01.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t02:
    short_name: "cudacoder_gspo_qwen32b_t02"
    config_path: "shared/config/workflow/cudacoder_gspo_qwen32b.t02.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t03:
    short_name: "cudacoder_gspo_qwen32b_t03"
    config_path: "shared/config/workflow/cudacoder_gspo_qwen32b.t03.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t04:
    short_name: "cudacoder_gspo_qwen32b_t04"
    config_path: "shared/config/workflow/cudacoder_gspo_qwen32b.t04.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t05:
    short_name: "cudacoder_gspo_qwen32b_t05"
    config_path: "shared/config/workflow/cudacoder_gspo_qwen32b.t05.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t06:
    short_name: "cudacoder_gspo_qwen32b_t06"
    config_path: "shared/config/workflow/cudacoder_gspo_qwen32b.t06.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t07:
    short_name: "cudacoder_gspo_qwen32b_t07"
    config_path: "shared/config/workflow/cudacoder_gspo_qwen32b.t07.yaml"
    data_dir: "shared/.workflow"

providers:
  default:
    host: "devvm8492.cco0.facebook.com"
    port: 8488
    retries: 5
    timeout: 300

  h8_3:
    host: "devvm8490.cco0.facebook.com"
    port: 8488
    retries: 5
    timeout: 300

  h8_5:
    host: "devvm8492.cco0.facebook.com"
    port: 8488
    retries: 5
    timeout: 300

# fastapi server
servers:
  default:
    host: "::"
    port: 8488
  one:
    host: 0.0.0.0
    port: 41488
  two:
    host: 0.0.0.0
    port: 42488
  four:
    host: 0.0.0.0
    port: 44488
  dequeue_timeout: 5
  devgpu139.cco2.facebook.com:
    host: "::"
    port: 8488
  devvm8492.cco0.facebook.com:
    host: "::"
    port: 8488


_refresh_config_task:
  interval: 15

_refresh_workflow_task:
  interval: 15

_save_queue_task:
  interval: 15

_save_adapter_task:
  interval: 15
