registry:
  TC_0.1.0_32B.c:
    short_name: "t32c"
    config_path: "workflow/32B.c.yaml"
    data_dir: "~/.workflow"
  TC_0.1.0_32B.d:
    short_name: "t32d"
    config_path: "workflow/32B.d.yaml"
    data_dir: "~/.workflow"
  TC_0.1.0_32B.e:
    short_name: "t32e"
    config_path: "workflow/32B.e.yaml"
    data_dir: "~/.workflow"
  TC_0.1.0_32B.f:
    short_name: "t32f"
    config_path: "workflow/32B.f.yaml"
    data_dir: "~/.workflow"
  TC_0.1.0_32B.g:
    short_name: "t32g"
    config_path: "workflow/32B.g.yaml"
    data_dir: "~/.workflow"
  TC_0.1.0_32B.h:
    short_name: "t32h"
    config_path: "workflow/32B.h.yaml"
    data_dir: "~/.workflow"
  test: # please do not remove, this is used by unit tests
    short_name: "test"
    config_path: "workflow/test.yaml"
    data_dir: "~/.workflow"
  claude_code: # Claude Code kernel bench integration
    short_name: "cc"
    config_path: "workflow/claude_code.yaml"
    data_dir: "~/.workflow"
  my_tag.a:
    short_name: "ma"
    config_path: "workflow/my_tag.a.yaml"
    data_dir: "shared/.workflow"
  cudacoder_eval_one_turn.test: # run make sync_config to update the config file in the shared folder
    short_name: "cudacoder_eval2"
    config_path: "workflow/cudacoder_eval_one_turn.test.yaml"
    data_dir: "shared/.workflow"
  cudacoder_eval_4_turn.qwen32b:
    short_name: "cudacoder_eval_4"
    config_path: "workflow/cudacoder_eval_4_turn.qwen32b.yaml"
    data_dir: "shared/.workflow"
  cudacoder_eval_4_turn.qwen32b_hardtasks:
    short_name: "cudacoder_eval_4"
    config_path: "workflow/cudacoder_eval_4_turn.qwen32b_hardtasks.yaml"
    data_dir: "shared/.workflow"
  cudacoder_eval_4_turn.qwen32b_repeat:
    short_name: "cudacoder_eval_4"
    config_path: "workflow/cudacoder_eval_4_turn.qwen32b_repeat.yaml"
    data_dir: "shared/.workflow"
  cudacoder_eval_4_turn.qwen32b_repeatv2:
    short_name: "cudacoder_evalv2_4"
    config_path: "workflow/cudacoder_eval_4_turn.qwen32b_repeatv2.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t01:
    short_name: "cudacoder_gspo_qwen32b_t01"
    config_path: "workflow/cudacoder_gspo_qwen32b.t01.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t02:
    short_name: "cudacoder_gspo_qwen32b_t02"
    config_path: "workflow/cudacoder_gspo_qwen32b.t02.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t03:
    short_name: "cudacoder_gspo_qwen32b_t03"
    config_path: "workflow/cudacoder_gspo_qwen32b.t03.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t04:
    short_name: "cudacoder_gspo_qwen32b_t04"
    config_path: "workflow/cudacoder_gspo_qwen32b.t04.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t05:
    short_name: "cudacoder_gspo_qwen32b_t05"
    config_path: "workflow/cudacoder_gspo_qwen32b.t05.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t06:
    short_name: "cudacoder_gspo_qwen32b_t06"
    config_path: "workflow/cudacoder_gspo_qwen32b.t06.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t07:
    short_name: "cudacoder_gspo_qwen32b_t07"
    config_path: "workflow/cudacoder_gspo_qwen32b.t07.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t08:
    short_name: "cudacoder_gspo_qwen32b_t08"
    config_path: "workflow/cudacoder_gspo_qwen32b.t08.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t09:
    short_name: "cudacoder_gspo_qwen32b_t09"
    config_path: "workflow/cudacoder_gspo_qwen32b.t09.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t10:
    short_name: "cudacoder_gspo_qwen32b_t10"
    config_path: "workflow/cudacoder_gspo_qwen32b.t10.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t11:
    short_name: "cudacoder_gspo_qwen32b_t11"
    config_path: "workflow/cudacoder_gspo_qwen32b.t11.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t11t:
    short_name: "cudacoder_gspo_qwen32b_t11t"
    config_path: "workflow/cudacoder_gspo_qwen32b.t11t.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t12:
    short_name: "cudacoder_gspo_qwen32b_t12"
    config_path: "workflow/cudacoder_gspo_qwen32b.t12.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t13:
    short_name: "cudacoder_gspo_qwen32b_t13"
    config_path: "workflow/cudacoder_gspo_qwen32b.t13.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t14:
    short_name: "cudacoder_gspo_qwen32b_t14"
    config_path: "workflow/cudacoder_gspo_qwen32b.t14.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t15:
    short_name: "cudacoder_gspo_qwen32b_t15"
    config_path: "workflow/cudacoder_gspo_qwen32b.t15.yaml"
    data_dir: "shared/.workflow"
  cudacoder_gspo_qwen32b.t16:
    short_name: "cudacoder_gspo_qwen32b_t16"
    config_path: "workflow/cudacoder_gspo_qwen32b.t16.yaml"
    data_dir: "shared/.workflow"
  cudacoder_uft_qwen32b.t01:
    short_name: "cudacoder_uft_qwen32b_t01"
    config_path: "workflow/cudacoder_uft_qwen32b.t01.yaml"
    data_dir: "shared/.workflow"
  cudacoder_uft_qwen32b.t02:
    short_name: "cudacoder_uft_qwen32b_t02"
    config_path: "workflow/cudacoder_uft_qwen32b.t02.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t01:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t01"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t01.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02b:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02b"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02b.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02c:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02c"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02c.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02d:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02d"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02d.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02e:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02e"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02e.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02f:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02f"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02f.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02g:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02g"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02g.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02h:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02h"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02h.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02i:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02i"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02i.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02j:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02j"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02j.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02k:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02k"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02k.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02l:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02l"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02l.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02m:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02m"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02m.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t02n:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t02n"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t02n.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t03:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t03"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t03.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t04:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t04"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t04.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t05:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t05"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t05.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns_gspo_qwen32b.t06:
    short_name: "cudacoder_treeturns_gspo_qwen32b_t06"
    config_path: "workflow/cudacoder_treeturns_gspo_qwen32b.t06.yaml"
    data_dir: "shared/.workflow"
  cudacoder_eval_4_treeturns.qwen32b:
    short_name: "cudacoder_eval_4_treeturns_qwen32b"
    config_path: "workflow/cudacoder_eval_4_treeturns.qwen32b.yaml"
    data_dir: "shared/.workflow"
  cudacoder_treeturns.prompt_exp01:
    short_name: "cudacoder_treeturns.prompt_exp01"
    config_path: "workflow/cudacoder_treeturns.prompt_exp01.yaml"
    data_dir: "shared/.workflow"
  triton_eval.qwen32b.v0:
    short_name: "triton_eval.qwen32b.v0"
    config_path: "workflow/triton_eval.qwen32b.v0.yaml"
    data_dir: "shared/.workflow"
  cudacoder_eval_4_turn.qwen32b.gepat19:
    short_name: "cudacoder_eval_4_turn.qwen32b.gepat19"
    config_path: "workflow/cudacoder_eval_4_turn.qwen32b.gepat19.yaml"
    data_dir: "shared/.workflow"

providers:
  default:
    host: "devvm8492.cco0.facebook.com"
    port: 8488
    retries: 5
    timeout: 300

  local:
    host: "localhost"
    port: 8488
    retries: 3
    timeout: 60

  h8_3:
    host: "devvm8490.cco0.facebook.com"
    port: 8488
    retries: 5
    timeout: 300

  h8_5:
    host: "devvm8492.cco0.facebook.com"
    port: 8488
    retries: 5
    timeout: 300

  h8_1:
    host: "devvm8491.cco0.facebook.com"
    port: 8488
    retries: 5
    timeout: 300

# fastapi server
servers:
  default:
    host: "::"
    port: 8488
  one:
    host: 0.0.0.0
    port: 41488
  two:
    host: 0.0.0.0
    port: 42488
  four:
    host: 0.0.0.0
    port: 44488
  dequeue_timeout: 5
  devgpu139.cco2.facebook.com:
    host: "::"
    port: 8488
  devvm8491.cco0.facebook.com:
    host: "::"
    port: 8488
  devvm8492.cco0.facebook.com:
    host: "::"
    port: 8488


_refresh_config_task:
  interval: 15

_refresh_workflow_task:
  interval: 15

_save_queue_task:
  interval: 15

_save_adapter_task:
  interval: 15
