# fastapi server
fastapi:
  one:
    host: 0.0.0.0
    port: 41488
  two:
    host: 0.0.0.0
    port: 42488
  four:
    host: 0.0.0.0
    port: 44488
  h1:
    host: "::"
    port: 8488
  dequeue_timeout: 5
  devgpu139.cco2.facebook.com:
    host: "::"
    port: 8488

client:
  host: devgpu139.cco2.facebook.com
  port: 8488
  retries: 5
  timeout: 300

registry:
  TC_0.1.0_14B.m:
    short_name: "t14m"
    config_path: "workflow/14B.m.yaml"
    data_dir: "shared/.workflow"
  TC_0.1.0_14B.n:
    short_name: "t14n"
    config_path: "workflow/14B.n.yaml"
    data_dir: "shared/.workflow"
  TC_0.1.0_32B.a:
    short_name: "t32a"
    config_path: "workflow/32B.a.yaml"
    data_dir: "shared/.workflow"
  TC_0.1.0_32B.b:
    short_name: "t32b"
    config_path: "workflow/32B.b.yaml"
    data_dir: "shared/.workflow"
  test:
    short_name: "test"
    config_path: "workflow/test.yaml"
    data_dir: "shared/.workflow"
  my_tag.a:
    short_name: "ma"
    config_path: "workflow/my_tag.a.yaml"
    data_dir: "shared/.workflow"
  cudacoder_eval_one_turn.a:
    short_name: "cudacoder_eval"
    config_path: "workflow/cudacoder_eval.a.yaml"
    data_dir: "shared/.workflow"

# built-in tasks
_refresh_config_task:
  interval: 15

_refresh_workflow_task:
  interval: 15

_save_queue_task:
  interval: 15

_save_adapter_task:
  interval: 15
